name: Deploy a Django app to App Service

on: [push]

jobs:
  build:
    
    runs-on: ubuntu-18.04

    container:
      image: debian:stretch

    steps:
    - uses: actions/checkout@v1

    # Set Python version (https://github.com/actions/setup-python)
    - uses: actions/setup-python@v1
      with:
        python-version: '3.7.4' 
        architecture: 'x64' # What's our bitness on Linux?

    - name: Install modules and zip the project files
      run: |
        apt-get update
        apt-get install python3-dev default-libmysqlclient-dev
        python -m venv antenv --copies
        source antenv/bin/activate
        pip install -r requirements.txt

    # Finally, deploy the app to App Serv ice (https://github.com/Azure/webapps-deploy)
    - uses: azure/webapps-deploy@v1
      with:
        app-name: kichallapy
        publish-profile: ${{ secrets.PUBLISH_PROFILE }}

        # Startup script: 
        # apt-get install -y gcc && pip3 install -r requirements.txt && gunicorn --bind=0.0.0.0 --timeout 600 mydjangoproject.wsgi
